apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: 'istio_requests_total{destination_service_name!="",destination_service_namespace!="",response_code!~"5.*"}'
      resources:
        overrides:
          destination_service_namespace: {resource: "namespace"}
          destination_service_name: {resource: "service"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'round(sum(irate(<<.Series>>{reporter="destination",<<.LabelMatchers>>,response_code!~"5.*"}[5m])) by (destination_service_name), 0.001)'
    - seriesQuery: 'istio_request_duration_milliseconds_bucket{reporter="destination",destination_service_name!="",destination_service_namespace!="",response_code!~"5.*"}'
      resources:
        overrides:
          destination_service_namespace: {resource: "namespace"}
          destination_service_name: {resource: "service"}
      name:
        matches: "^(.*)_bucket"
        as: "${1}_p90"
      metricsQuery: 'histogram_quantile(0.90, sum(rate(<<.Series>>{reporter="destination",<<.LabelMatchers>>,response_code!~"5.*"}[1m])) by (le,destination_service_name))/1000'
